### ISSUE TITLE
VGG16 size is 224,224

### ISSUE THREAD

**Issue by hebuterzjj** [mintanwei/Cycle-IR#3]
Hi,

I try to implement your code.

I downloaded VGG16 model from https://github.com/machrisaa/tensorflow-vgg and put it in my_vgg folder. However, when I run the program, it shows the log like this. Could you help me with this error? Thank you.

`E:\ProgramData\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
npy file loaded
build model started
Traceback (most recent call last):

  File "<ipython-input-1-701a94e4a7d0>", line 1, in <module>
    runfile('F:/code/Cycle-IR-master/Cycle-IR-master/train_CycleIR.py', wdir='F:/code/Cycle-IR-master/Cycle-IR-master')

  File "E:\ProgramData\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 705, in runfile
    execfile(filename, namespace)

  File "E:\ProgramData\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "F:/code/Cycle-IR-master/Cycle-IR-master/train_CycleIR.py", line 208, in <module>
    tf.app.run()

  File "E:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\platform\app.py", line 125, in run
    _sys.exit(main(argv))

  File "F:/code/Cycle-IR-master/Cycle-IR-master/train_CycleIR.py", line 160, in main
    opt_g, aspect_ratio, images, CycleLoss, images_LR, AttentionMap, input_size, Sh, Sw = build_graph()

  File "F:/code/Cycle-IR-master/Cycle-IR-master/train_CycleIR.py", line 79, in build_graph
    Sh, Sw, AttentionMap = CycleIR(images, reuse=False)

  File "F:/code/Cycle-IR-master/Cycle-IR-master/train_CycleIR.py", line 22, in CycleIR
    vgg.build(images)

  File "F:\code\Cycle-IR-master\Cycle-IR-master\VGG_MODEL\vgg16.py", line 36, in build
    assert red.get_shape().as_list()[1:] == [224, 224, 1]

AssertionError`

**Comment by canopyPanda** [comment]
> Hi,
> 
> I try to implement your code.
> 
> I downloaded VGG16 model from https://github.com/machrisaa/tensorflow-vgg and put it in my_vgg folder. However, when I run the program, it shows the log like this. Could you help me with this error? Thank you.
> 
> `E:\ProgramData\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float`to`np.floating`is deprecated. In future, it will be treated as`np.float64 == np.dtype(float).type`.
> from ._conv import register_converters as _register_converters
> npy file loaded
> build model started
> Traceback (most recent call last):
> 
> File "", line 1, in 
> runfile('F:/code/Cycle-IR-master/Cycle-IR-master/train_CycleIR.py', wdir='F:/code/Cycle-IR-master/Cycle-IR-master')
> 
> File "E:\ProgramData\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 705, in runfile
> execfile(filename, namespace)
> 
> File "E:\ProgramData\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 102, in execfile
> exec(compile(f.read(), filename, 'exec'), namespace)
> 
> File "F:/code/Cycle-IR-master/Cycle-IR-master/train_CycleIR.py", line 208, in 
> tf.app.run()
> 
> File "E:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\platform\app.py", line 125, in run
> _sys.exit(main(argv))
> 
> File "F:/code/Cycle-IR-master/Cycle-IR-master/train_CycleIR.py", line 160, in main
> opt_g, aspect_ratio, images, CycleLoss, images_LR, AttentionMap, input_size, Sh, Sw = build_graph()
> 
> File "F:/code/Cycle-IR-master/Cycle-IR-master/train_CycleIR.py", line 79, in build_graph
> Sh, Sw, AttentionMap = CycleIR(images, reuse=False)
> 
> File "F:/code/Cycle-IR-master/Cycle-IR-master/train_CycleIR.py", line 22, in CycleIR
> vgg.build(images)
> 
> File "F:\code\Cycle-IR-master\Cycle-IR-master\VGG_MODEL\vgg16.py", line 36, in build
> assert red.get_shape().as_list()[1:] == [224, 224, 1]
> 
> AssertionError`

用这个代码，https://github.com/machrisaa/tensorflow-vgg
你这个问题是因为他这个网络是没有把输入crop成统一大小的，你把assert大小相关的都注释掉就好
注释掉之后我还报了全连接层的错误，你把全链接相关的也注释掉就好，这个是个全卷积网络

**Comment by yujingxin** [comment]
> > Hi,
> > I try to implement your code.
> > I downloaded VGG16 model from https://github.com/machrisaa/tensorflow-vgg and put it in my_vgg folder. However, when I run the program, it shows the log like this. Could you help me with this error? Thank you.
> > `E:\ProgramData\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float`to`np.floating`is deprecated. In future, it will be treated as`np.float64 == np.dtype(float).type`.
> > from ._conv import register_converters as _register_converters
> > npy file loaded
> > build model started
> > Traceback (most recent call last):
> > File "", line 1, in
> > runfile('F:/code/Cycle-IR-master/Cycle-IR-master/train_CycleIR.py', wdir='F:/code/Cycle-IR-master/Cycle-IR-master')
> > File "E:\ProgramData\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 705, in runfile
> > execfile(filename, namespace)
> > File "E:\ProgramData\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 102, in execfile
> > exec(compile(f.read(), filename, 'exec'), namespace)
> > File "F:/code/Cycle-IR-master/Cycle-IR-master/train_CycleIR.py", line 208, in
> > tf.app.run()
> > File "E:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\platform\app.py", line 125, in run
> > _sys.exit(main(argv))
> > File "F:/code/Cycle-IR-master/Cycle-IR-master/train_CycleIR.py", line 160, in main
> > opt_g, aspect_ratio, images, CycleLoss, images_LR, AttentionMap, input_size, Sh, Sw = build_graph()
> > File "F:/code/Cycle-IR-master/Cycle-IR-master/train_CycleIR.py", line 79, in build_graph
> > Sh, Sw, AttentionMap = CycleIR(images, reuse=False)
> > File "F:/code/Cycle-IR-master/Cycle-IR-master/train_CycleIR.py", line 22, in CycleIR
> > vgg.build(images)
> > File "F:\code\Cycle-IR-master\Cycle-IR-master\VGG_MODEL\vgg16.py", line 36, in build
> > assert red.get_shape().as_list()[1:] == [224, 224, 1]
> > AssertionError`
> 
> 用这个代码，https://github.com/machrisaa/tensorflow-vgg
> 你这个问题是因为他这个网络是没有把输入crop成统一大小的，你把assert大小相关的都注释掉就好
> 注释掉之后我还报了全连接层的错误，你把全链接相关的也注释掉就好，这个是个全卷积网络

请问你们训练能收敛吗？我这里调参也不太行一直在震荡。

**Comment by canopyPanda** [comment]
> > > Hi,
> > > I try to implement your code.
> > > I downloaded VGG16 model from https://github.com/machrisaa/tensorflow-vgg and put it in my_vgg folder. However, when I run the program, it shows the log like this. Could you help me with this error? Thank you.
> > > `E:\ProgramData\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float`to`np.floating`is deprecated. In future, it will be treated as`np.float64 == np.dtype(float).type`. from ._conv import register_converters as _register_converters npy file loaded build model started Traceback (most recent call last): File "", line 1, in runfile('F:/code/Cycle-IR-master/Cycle-IR-master/train_CycleIR.py', wdir='F:/code/Cycle-IR-master/Cycle-IR-master') File "E:\ProgramData\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 705, in runfile execfile(filename, namespace) File "E:\ProgramData\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 102, in execfile exec(compile(f.read(), filename, 'exec'), namespace) File "F:/code/Cycle-IR-master/Cycle-IR-master/train_CycleIR.py", line 208, in tf.app.run() File "E:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\platform\app.py", line 125, in run _sys.exit(main(argv)) File "F:/code/Cycle-IR-master/Cycle-IR-master/train_CycleIR.py", line 160, in main opt_g, aspect_ratio, images, CycleLoss, images_LR, AttentionMap, input_size, Sh, Sw = build_graph() File "F:/code/Cycle-IR-master/Cycle-IR-master/train_CycleIR.py", line 79, in build_graph Sh, Sw, AttentionMap = CycleIR(images, reuse=False) File "F:/code/Cycle-IR-master/Cycle-IR-master/train_CycleIR.py", line 22, in CycleIR vgg.build(images) File "F:\code\Cycle-IR-master\Cycle-IR-master\VGG_MODEL\vgg16.py", line 36, in build assert red.get_shape().as_list()[1:] == [224, 224, 1] AssertionError`
> > 
> > 
> > 用这个代码，https://github.com/machrisaa/tensorflow-vgg
> > 你这个问题是因为他这个网络是没有把输入crop成统一大小的，你把assert大小相关的都注释掉就好
> > 注释掉之后我还报了全连接层的错误，你把全链接相关的也注释掉就好，这个是个全卷积网络
> 
> 请问你们训练能收敛吗？我这里调参也不太行一直在震荡。

并不能收敛。。

**Comment by SuperReally** [comment]
> > > > Hi,
> > > > I try to implement your code.
> > > > I downloaded VGG16 model from https://github.com/machrisaa/tensorflow-vgg and put it in my_vgg folder. However, when I run the program, it shows the log like this. Could you help me with this error? Thank you.
> > > > `E:\ProgramData\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float`to`np.floating`is deprecated. In future, it will be treated as`np.float64 == np.dtype(float).type`. from ._conv import register_converters as _register_converters npy file loaded build model started Traceback (most recent call last): File "", line 1, in runfile('F:/code/Cycle-IR-master/Cycle-IR-master/train_CycleIR.py', wdir='F:/code/Cycle-IR-master/Cycle-IR-master') File "E:\ProgramData\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 705, in runfile execfile(filename, namespace) File "E:\ProgramData\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 102, in execfile exec(compile(f.read(), filename, 'exec'), namespace) File "F:/code/Cycle-IR-master/Cycle-IR-master/train_CycleIR.py", line 208, in tf.app.run() File "E:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\platform\app.py", line 125, in run _sys.exit(main(argv)) File "F:/code/Cycle-IR-master/Cycle-IR-master/train_CycleIR.py", line 160, in main opt_g, aspect_ratio, images, CycleLoss, images_LR, AttentionMap, input_size, Sh, Sw = build_graph() File "F:/code/Cycle-IR-master/Cycle-IR-master/train_CycleIR.py", line 79, in build_graph Sh, Sw, AttentionMap = CycleIR(images, reuse=False) File "F:/code/Cycle-IR-master/Cycle-IR-master/train_CycleIR.py", line 22, in CycleIR vgg.build(images) File "F:\code\Cycle-IR-master\Cycle-IR-master\VGG_MODEL\vgg16.py", line 36, in build assert red.get_shape().as_list()[1:] == [224, 224, 1] AssertionError`
> > > 
> > > 
> > > 用这个代码，https://github.com/machrisaa/tensorflow-vgg
> > > 你这个问题是因为他这个网络是没有把输入crop成统一大小的，你把assert大小相关的都注释掉就好
> > > 注释掉之后我还报了全连接层的错误，你把全链接相关的也注释掉就好，这个是个全卷积网络
> > 
> > 
> > 请问你们训练能收敛吗？我这里调参也不太行一直在震荡。
> 
> 并不能收敛。。

我得到的图片每一次效果都不一样

**Comment by givkashi** [comment]
Hi everyone. if you can train or use this repository let me know. Thanks.
Did you solve your problem? how can you implement this repository? @SuperReally 
Did you share your implementation? @canopyPanda 
Did you run these codes? @hebuterzjj
