### ISSUE TITLE
在训练的时候总是报这个错误，是训练数据有问题吗？大概迭代到5000的时候，batchsize设置为2的话，迭代到4000多就开始报错了

### ISSUE THREAD

**Issue by cherryolg** [mintanwei/Cycle-IR#7]
Traceback (most recent call last):
  File "/home/Anaconda3/envs/tf18/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1322, in _do_call
    return fn(*args)
  File "/home/Anaconda3/envs/tf18/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1307, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/home/Anaconda3/envs/tf18/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1409, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Requested more than 0 entries, but params is empty.  Params shape: [0,0,3]
	 [[Node: while/GatherNd_2 = GatherNd[Tindices=DT_INT32, Tparams=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"](while/transpose_1, while/stack_3/_10383)]]
	 [[Node: while_3/cond_1/while/cond/mul_8/_10811 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_29310_while_3/cond_1/while/cond/mul_8", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"](^_cloopwhile_3/cond_1/while/Identity/_171)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train_CycleIR.py", line 208, in <module>
    tf.app.run()
  File "/home/Anaconda3/envs/tf18/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "train_CycleIR.py", line 196, in main
    _, generator_loss = sess.run([opt_g, CycleLoss], feed_dict=feed_dict)
  File "/home/Anaconda3/envs/tf18/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 900, in run
    run_metadata_ptr)
  File "/home/Anaconda3/envs/tf18/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1135, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/Anaconda3/envs/tf18/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1316, in _do_run
    run_metadata)
  File "/home/Anaconda3/envs/tf18/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1335, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Requested more than 0 entries, but params is empty.  Params shape: [0,0,3]
	 [[Node: while/GatherNd_2 = GatherNd[Tindices=DT_INT32, Tparams=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"](while/transpose_1, while/stack_3/_10383)]]
	 [[Node: while_3/cond_1/while/cond/mul_8/_10811 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_29310_while_3/cond_1/while/cond/mul_8", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"](^_cloopwhile_3/cond_1/while/Identity/_171)]]

Caused by op 'while/GatherNd_2', defined at:
  File "train_CycleIR.py", line 208, in <module>
    tf.app.run()
  File "/home/Anaconda3/envs/tf18/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "train_CycleIR.py", line 160, in main
    opt_g, aspect_ratio, images, CycleLoss, images_LR, AttentionMap, input_size, Sh, Sw = build_graph()
  File "train_CycleIR.py", line 80, in build_graph
    images_LR = reconstruct_image(images, Sh, Sw, input_size, aspect_ratio)
  File "/home/zm/wd/Cycle-IR/Circle_reconstruct_image.py", line 85, in reconstruct_image
    ta_final_result = resize_images(images, aspect_ratio, input_size, B, M, N, newH, newW)
  File "/home/zm/wd/Cycle-IR/Circle_reconstruct_image.py", line 38, in resize_images
    n, img_final = tf.while_loop(condition, body, init_state)
  File "/home/Anaconda3/envs/tf18/lib/python3.5/site-packages/tensorflow/python/ops/control_flow_ops.py", line 3224, in while_loop
    result = loop_context.BuildLoop(cond, body, loop_vars, shape_invariants)
  File "/home/Anaconda3/envs/tf18/lib/python3.5/site-packages/tensorflow/python/ops/control_flow_ops.py", line 2956, in BuildLoop
    pred, body, original_loop_vars, loop_vars, shape_invariants)
  File "/home/Anaconda3/envs/tf18/lib/python3.5/site-packages/tensorflow/python/ops/control_flow_ops.py", line 2893, in _BuildLoop
    body_result = body(*packed_vars_for_body)
  File "/home/zm/wd/Cycle-IR/Circle_reconstruct_image.py", line 35, in body
    ta_final_result = ResizeImage(ta_final_result, tf.constant([1., 0, 0, 0, 1., 0]), out_dims=out_dims)
  File "/home/zm/wd/Cycle-IR/image_resizing.py", line 14, in ResizeImage
    out_fmap = bilinear_sampler(input_fmap, x_s, y_s)
  File "/home/zm/wd/Cycle-IR/image_resizing.py", line 72, in bilinear_sampler
    Ic = get_pixel_value(img, x1, y0)  # x0, y0-1
  File "/home/zm/wd/Cycle-IR/image_resizing.py", line 20, in get_pixel_value
    return tf.gather_nd(img, indices)
  File "/home/Anaconda3/envs/tf18/lib/python3.5/site-packages/tensorflow/python/ops/gen_array_ops.py", line 2975, in gather_nd
    "GatherNd", params=params, indices=indices, name=name)
  File "/home/Anaconda3/envs/tf18/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/Anaconda3/envs/tf18/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 3392, in create_op
    op_def=op_def)
  File "/home/Anaconda3/envs/tf18/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1718, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): Requested more than 0 entries, but params is empty.  Params shape: [0,0,3]
	 [[Node: while/GatherNd_2 = GatherNd[Tindices=DT_INT32, Tparams=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"](while/transpose_1, while/stack_3/_10383)]]
	 [[Node: while_3/cond_1/while/cond/mul_8/_10811 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_29310_while_3/cond_1/while/cond/mul_8", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"](^_cloopwhile_3/cond_1/while/Identity/_171)]]

**Comment by kiashann** [comment]
Hi there, I need train_CycleIR.py file, could you please share with me?
@cherryolg

**Comment by cherryolg** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "mintanwei/Cycle-IR"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月31日(星期一) 晚上9:49
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [mintanwei/Cycle-IR] 在训练的时候总是报这个错误，是训练数据有问题吗？大概迭代到5000的时候，batchsize设置为2的话，迭代到4000多就开始报错了 (#7)





 
Hi there, I need train_CycleIR.py file, could you please share with me?
 @cherryolg
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by kiashann** [comment]
I can't understand your answer please type in English.
I saw train_CycleIR.py in commit history but I couldn't run this codes without error. Can you train this codes and solve errors?

@cherryolg

**Comment by cherryolg** [comment]
I'm sorry to see your reply just now. I didn't run this code successfully, and I abandoned it later. I'm sorry I can't help you!





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "mintanwei/Cycle-IR"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年2月8日(星期二) 晚上8:09
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [mintanwei/Cycle-IR] 在训练的时候总是报这个错误，是训练数据有问题吗？大概迭代到5000的时候，batchsize设置为2的话，迭代到4000多就开始报错了 (#7)





 
I can't understand your answer please type in English.
 I saw train_CycleIR.py in commit history but I couldn't run this codes without error. Can you train this codes and solve errors?
 
@cherryolg
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by zw-92** [comment]
> 我无法理解您的答案，请输入英文。

Hello, sorry to bother you. Did you successfully train the project and test the effects of the network? I am short of train_CycleIR.py file, I hope you can provide it to me. Thank you and look forward to your reply.

**Comment by zw-92** [comment]
> 我无法理解您的答案，请输入英文。我在提交历史记录中看到train_CycleIR.py，但我无法运行此代码而不会出错。你能训练这些代码并解决错误吗？
> 
> @cherryolg

我的邮箱369513570@qq.com
