### ISSUE TITLE
Not able to reproduce results

### ISSUE THREAD

**Issue by AlverGant** [mintanwei/Cycle-IR#8]
As far as I know this is the only project to do image retargeting with deep-learning.
Really interested to see it working..
Done with all requirements
Donwloaded vgg16.npy and vgg16.py from  https://github.com/machrisaa/tensorflow-vgg in VGG_MODEL folder
commented out all assert instructions from vgg16.py
Now stuck with this error

ubuntu@vega:~/Cycle-IR$ python3 CycleIR.py 
npy file loaded
build model started
Traceback (most recent call last):
  File "CycleIR.py", line 204, in <module>
    tf.app.run()
  File "/home/ubuntu/.local/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "CycleIR.py", line 190, in main
    opt_g, aspect_ratio, images, CycleLoss, images_LR, AttentionMap, input_size, Sh, Sw = build_graph()
  File "CycleIR.py", line 93, in build_graph
    Sh, Sw, AttentionMap = CycleIR(images, reuse=False)
  File "CycleIR.py", line 27, in CycleIR
    vgg.build(images)
  File "/home/ubuntu/Cycle-IR/VGG_MODEL/vgg16.py", line 69, in build
    self.fc6 = self.fc_layer(self.pool5, "fc6")
  File "/home/ubuntu/Cycle-IR/VGG_MODEL/vgg16.py", line 106, in fc_layer
    dim *= d
TypeError: unsupported operand type(s) for *=: 'int' and 'NoneType'

**Comment by givkashi** [comment]
Can you solve your problem? @AlverGant

**Comment by AlverGant** [comment]
@givkashi unfortunately no

**Comment by kiashann** [comment]
> As far as I know this is the only project to do image retargeting with deep-learning. Really interested to see it working.. Done with all requirements Donwloaded vgg16.npy and vgg16.py from https://github.com/machrisaa/tensorflow-vgg in VGG_MODEL folder commented out all assert instructions from vgg16.py Now stuck with this error
> 
> ubuntu@vega:~/Cycle-IR$ python3 CycleIR.py npy file loaded build model started Traceback (most recent call last): File "CycleIR.py", line 204, in tf.app.run() File "/home/ubuntu/.local/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 126, in run _sys.exit(main(argv)) File "CycleIR.py", line 190, in main opt_g, aspect_ratio, images, CycleLoss, images_LR, AttentionMap, input_size, Sh, Sw = build_graph() File "CycleIR.py", line 93, in build_graph Sh, Sw, AttentionMap = CycleIR(images, reuse=False) File "CycleIR.py", line 27, in CycleIR vgg.build(images) File "/home/ubuntu/Cycle-IR/VGG_MODEL/vgg16.py", line 69, in build self.fc6 = self.fc_layer(self.pool5, "fc6") File "/home/ubuntu/Cycle-IR/VGG_MODEL/vgg16.py", line 106, in fc_layer dim *= d TypeError: unsupported operand type(s) for *=: 'int' and 'NoneType'

Did you find any solution for train this code? 
I can't find **train_CycleIR.py** file in this repository
